// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://rvjbileoduklvoqtskoz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJ2amJpbGVvZHVrbHZvcXRza296Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjMwNTQyNTksImV4cCI6MjA3ODYzMDI1OX0._nqEmIndLJXDs0Faf7ZHUkJSq5mZHC9kbT24EqyQRYo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);